from setuptools import setup, find_packages

setup(
    name="research-paper-analysis",
    version="0.1.0",
    description="Research Paper Analysis & Classification Pipeline",
    author="Your Name",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "transformers>=4.30.0",
        "datasets>=2.12.0",
        "accelerate>=0.20.0",
        "peft>=0.4.0",
        "bitsandbytes>=0.41.0",
        "scikit-learn>=1.3.0",
        "pandas>=2.0.0",
        "numpy>=1.24.0",
        "fastapi>=0.100.0",
        "uvicorn>=0.23.0",
        "pydantic>=2.0.0",
        "langchain>=0.0.267",
        "langchain-community>=0.0.10",
        "python-multipart>=0.0.6",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "tqdm>=4.65.0",
        "requests>=2.31.0",
        "beautifulsoup4>=4.12.0",
        "lxml>=4.9.0",
        "nltk>=3.8.0",
        "spacy>=3.6.0",
    ],
    python_requires=">=3.8",
) 